site_name: DerivaML
site_url: https://informatics-isi-edu.github.io/deriva-ml
theme:
   name: material
   palette:
      scheme: slate
      primary: green
      accent: purple

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx