site_name: DerivaML
site_url: https://informatics-isi-edu.github.io/deriva-ml
theme:
   name: material
   logo: assets/deriva-logo.png
   features:
       - navigation.instant
       - navigation.expand
       - navigation.footer
   palette:
      scheme: slate
      primary: black
      accent: blue
   copyright: "© Copyright 2025, USC Information Sciences Institute, Informatics Systems Research Division."

plugins:
- search

- mkdocstrings:
    handlers:
      python:
        paths:
          - src  # Search for modules in the 'src' directory
        options:
          docstring_style: sphinx
          separate_signature: true
          show_signature_annotations: true
          line_length: 40
          annotations_path: brief
- mkdocs-jupyter:
   include: ["*.ipynb"]
   include_source: True

nav:
  - Home: index.md
  - User Guide:
    - Creating a workflow: ml_workflow_instruction.md
    - DerivaML Structure: deriva_ml_structure.md
    - VM Docs: VM_setup_instruction.md
  - Notebooks:
    - Datasets: 'Notebooks/DerivaML Dataset.ipynb'
    - Execution: 'Notebooks/DerivaML Execution.ipynb'
    - Features : 'Notebooks/DerivaML Features.ipynb'
    - Vocabulary: 'Notebooks/DerivaML Vocabulary.ipynb'
  - Library Documentation:
    - DerivaML: deriva_ml_base.md
    - DatasetBag: dataset_bag.md
    - Execution: execution.md
    - ExecutionConfiguration: execution_configuration.md
  - Release Notes: release-notes.md
