[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deriva-ml"
version = "0.0.2"
authors = [
    {name = "ISRD", email = "isrd-dev@isi.edu"},
]
description = "Utilities to simplify use of Dervia and Pandas"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
deriva-ml-validate-configuration = "deriva_ml.validate_configuration:main"
deriva-ml-table-comments-utils = "deriva_ml.schema_setup.table_comments_utils:main"
deriva-ml-create-schema = "deriva_ml.schema_setup.create_schema:main"
deriva-ml-alter-annotation = "deriva_ml.schema_setup.alter_annotation:main"

[metadata]
license = "Apache 2.0"
keywords = ["deriva-ml"]