[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deriva-ml"
version = "0.0.1"
authors = [
    {name = "Your Name", email = "you@yourdomain.com"},
]
description = "Utilities to simplify use of Dervia and Pandas"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
deriva-ml-validate-configuration = "deriva_ml.validate_configuration:main"

[metadata]
license = "Apache 2.0"
keywords = ["deriva-ml"]