"""
This module provides functions that help structure local directories for uploading to a DerivaML catalog, and
generating an upload specification for those directories.

Here is the directory layout we support:

  deriva-ml/
       execution
           <execution_rid>
               execution-asset
                   <asset_type>
                       file1, file2, ....   <- Need to update execution_asset association table.
               execution-metadata
                   <metadata_type>
               feature
                   <schema>
                       <target_table>
                            <feature_name>
                                   asset
                                       <asset_table>
                                           file1, file2, ...
                           <feature_name>.jsonl    <- needs to have asset_name column remapped before uploading
                table
                   <schema>
                       <record_table>
                          record_table.csv
                asset
                    <schema>
                        <asset_table>
                            <metadata1>
                                <metadata2>
                                    file1, file2, ....
                asset-type
                    <schema>
                        file1.jsonl, file2.jsonl
"""

# Deriva imports - use importlib to avoid shadowing by local 'deriva.py' files
import importlib
import os
from pathlib import Path
from typing import Any

import regex as re

_deriva_core = importlib.import_module("deriva.core")
_ermrest_model = importlib.import_module("deriva.core.ermrest_model")
_hatrac_store = importlib.import_module("deriva.core.hatrac_store")
_hash_utils = importlib.import_module("deriva.core.utils.hash_utils")
_mime_utils = importlib.import_module("deriva.core.utils.mime_utils")
_deriva_upload = importlib.import_module("deriva.transfer.upload.deriva_upload")

urlquote = _deriva_core.urlquote
Table = _ermrest_model.Table
HatracStore = _hatrac_store.HatracStore
hash_utils = _hash_utils
mime_utils = _mime_utils
GenericUploader = _deriva_upload.GenericUploader
from pydantic import validate_call

from deriva_ml.core.definitions import (
    RID,
)
from deriva_ml.core.validation import VALIDATION_CONFIG
from deriva_ml.model.catalog import DerivaModel

NULL_SENTINEL = "__NULL__"
"""Directory-segment marker for nullable asset-metadata columns with
no value, retained for :class:`NullSentinelProcessor` and consumers
that still pass through the GenericUploader filesystem-pattern path
(e.g., the deriva-py upload spec generated by
:func:`asset_table_upload_spec`). The production bag-commit path
in :mod:`deriva_ml.execution.bag_commit` does not need this sentinel
— it ships real ``None`` values straight into
:class:`deriva.bag.BagBuilder`."""

# Use os.path.sep for OS-agnostic paths in regex patterns
SEP = re.escape(os.path.sep)
upload_root_regex = f"(?i)^.*{SEP}deriva-ml"

exec_dir_regex = upload_root_regex + f"{SEP}execution{SEP}(?P<execution_rid>[-\\w]+)"

asset_path_regex = exec_dir_regex + rf"{SEP}asset{SEP}(?P<schema>[-\w]+){SEP}(?P<asset_table>[-\w]*)"

asset_file_regex = r"(?P<file>[-\w]+)[.](?P<ext>[a-z0-9]*)$"

table_regex = exec_dir_regex + rf"{SEP}table{SEP}(?P<schema>[-\w]+){SEP}(?P<table>[-\w]+){SEP}(?P=table)[.](csv|json)$"


__all__ = [
    "NULL_SENTINEL",
    "upload_root",
    "execution_rids",
    "execution_root",
    "asset_root",
    "flat_asset_dir",
    "manifest_path",
    "table_path",
    "asset_type_path",
    "asset_table_upload_spec",
    "bulk_upload_configuration",
]


def upload_root(prefix: Path | str) -> Path:
    """Return the top level directory of where to put files to be uploaded."""
    path = Path(prefix) / "deriva-ml"
    path.mkdir(exist_ok=True, parents=True)
    return path


def execution_rids(prefix: Path | str) -> list[RID]:
    """Return all execution RIDs that have files staged for upload.

    Scans the ``execution/`` subdirectory under the upload root and returns the
    name of each immediate child directory, which corresponds to an execution RID.

    Args:
        prefix: Location of the upload root directory.

    Returns:
        List of execution RID strings found under the upload root.
    """
    path = upload_root(prefix) / "execution"
    return [d.name for d in path.iterdir()]


def execution_root(prefix: Path | str, exec_rid) -> Path:
    """Return the directory for staging upload files for a specific execution.

    The directory is created if it does not already exist.

    Args:
        prefix: Location of the upload root directory.
        exec_rid: RID of the execution whose upload files are being staged.

    Returns:
        Path to the execution-specific upload directory.
    """
    path = upload_root(prefix) / "execution" / exec_rid
    path.mkdir(exist_ok=True, parents=True)
    return path


def asset_root(prefix: Path | str, exec_rid: str) -> Path:
    """Return the directory for staging asset uploads for a specific execution.

    The directory is created if it does not already exist.

    Args:
        prefix: Location of the upload root directory.
        exec_rid: RID of the execution whose asset files are being staged.

    Returns:
        Path to the asset upload directory for the given execution.
    """
    path = execution_root(prefix, exec_rid) / "asset"
    path.mkdir(parents=True, exist_ok=True)
    return path


def flat_asset_dir(prefix: Path | str, exec_rid: str, asset_table_name: str) -> Path:
    """Return the flat per-table asset directory for the manifest-first storage layout.

    Files are stored in ``assets/{AssetTable}/`` without metadata encoding in the path.
    Metadata lives in the manifest JSON file instead.

    Args:
        prefix: Location of upload root directory.
        exec_rid: Execution RID.
        asset_table_name: Name of the asset table (e.g., "Image", "Model").

    Returns:
        Path to the flat asset directory (created if it doesn't exist).
    """
    path = execution_root(prefix, exec_rid) / "assets" / asset_table_name
    path.mkdir(parents=True, exist_ok=True)
    return path


def manifest_path(prefix: Path | str, exec_rid: str) -> Path:
    """Return the path to the asset-manifest.json file for an execution."""
    return execution_root(prefix, exec_rid) / "asset-manifest.json"


def table_path(prefix: Path | str, schema: str, table: str) -> Path:
    """Return the path to a CSV file in which to place table values that are to be uploaded.

    Args:
        prefix: Location of upload root directory
        schema: Domain schema
        table: Name of the table to be uploaded.

    Returns:
        Path to the file in which to place table values that are to be uploaded.
    """
    path = upload_root(prefix) / "table" / schema / table
    path.mkdir(parents=True, exist_ok=True)
    return path / f"{table}.csv"


def asset_table_upload_spec(model: DerivaModel, asset_table: str | Table, chunk_size: int | None = None):
    """Generate upload specification for an asset table.

    Args:
        model: The DerivaModel instance.
        asset_table: The asset table name or Table object.
        chunk_size: Optional chunk size in bytes for hatrac uploads. If provided,
            large files will be uploaded in chunks of this size.

    Returns:
        A dictionary containing the upload specification for the asset table.
    """
    # ``asset_metadata_sorted`` pins the alphabetic-order
    # invariant in one place — both this upload-spec builder
    # and the bag-commit row writer must produce columns in the
    # same order so the regex captures align with the recorded
    # values.
    metadata_columns = model.asset_metadata_sorted(asset_table)
    asset_table = model.name_to_table(asset_table)
    schema = model.name_to_table(asset_table).schema.name

    # Be careful here as a metadata value might be a string with can contain special characters.
    # metadata_columns is sorted to ensure deterministic directory order matching the regex.
    metadata_path = "/".join([rf"(?P<{c}>[-:._ \w]+)" for c in metadata_columns])
    # Bug E.2: capture pre-allocated RID as an additional path segment
    # after metadata columns and before the filename.
    rid_path = r"(?P<RID>[-A-Z0-9]+)"
    parts = [metadata_path, rid_path] if metadata_path else [rid_path]
    asset_path = f"{exec_dir_regex}/asset/{schema}/{asset_table.name}/{'/'.join(parts)}/{asset_file_regex}"
    asset_table = model.name_to_table(asset_table)
    schema = model.name_to_table(asset_table).schema.name

    # Build hatrac_options with optional chunk_size
    hatrac_options = {"versioned_urls": True}
    if chunk_size is not None:
        hatrac_options["chunk_size"] = chunk_size

    # Create upload specification
    spec = {
        # Upload assets into an asset table of an asset table.
        "column_map": {
            "MD5": "{md5}",
            "URL": "{URI}",
            "Length": "{file_size}",
            "Filename": "{file_name}",
            "RID": "{RID}",  # Bug E.2: pre-allocated RID
        }
        | {c: f"{{{c}}}" for c in metadata_columns},
        "file_pattern": asset_path,  # Sets schema, asset_table, file
        "asset_type": "file",
        "target_table": [schema, asset_table.name],
        "checksum_types": ["sha256", "md5"],
        "hatrac_options": hatrac_options,
        "hatrac_templates": {
            "hatrac_uri": f"/hatrac/{asset_table.name}/{{md5}}.{{file_name}}",
            "content-disposition": "filename*=UTF-8''{file_name}",
        },
        "record_query_template": "/entity/{target_table}/MD5={md5}&Filename={file_name}",
        "use_pre_allocated_rid": True,  # Bug E.2: use caller-supplied RID
    }
    # Wire the NullSentinelProcessor only when the table has metadata
    # columns — otherwise no sentinel values can appear and the
    # processor would be a no-op. See Bug C design doc.
    if metadata_columns:
        spec["pre_processors"] = [
            {
                "processor": "NullSentinelProcessor",
                "processor_type": ("deriva_ml.asset.null_sentinel_processor.NullSentinelProcessor"),
            }
        ]
    return spec


def bulk_upload_configuration(model: DerivaModel, chunk_size: int | None = None) -> dict[str, Any]:
    """Return an upload specification for deriva-ml

    Args:
        model: Model from which to generate the upload configuration.
        chunk_size: Optional chunk size in bytes for hatrac uploads. If provided,
            large files will be uploaded in chunks of this size.
    """
    # Bug E.2: Use asset_table_upload_spec for ALL asset tables, not
    # just those with metadata columns. The spec handles zero-metadata
    # tables correctly (RID is the only capturing segment). This
    # unifies the regex + use_pre_allocated_rid semantics across all
    # asset tables, fixing the mismatch where Execution_Metadata (and
    # other zero-metadata tables) went through a fallback mapping that
    # did not include the RID segment.
    all_asset_mappings = [
        asset_table_upload_spec(model=model, asset_table=t, chunk_size=chunk_size) for t in model.find_assets()
    ]

    return {
        "asset_mappings": all_asset_mappings
        + [
            {
                #  Upload the records into a  table
                "asset_type": "table",
                "default_columns": ["RID", "RCB", "RMB", "RCT", "RMT"],
                "file_pattern": table_regex,  # Sets schema, table,
                "ext_pattern": "^.*[.](?P<file_ext>json|csv)$",
                "target_table": ["{schema}", "{table}"],
            },
        ],
        "version_update_url": "https://github.com/informatics-isi-edu/deriva-client",
        "version_compatibility": [[">=1.4.0", "<2.0.0"]],
    }


# Default timeout for large file uploads in seconds.
# The requests timeout tuple is (connect_timeout, read_timeout).
# IMPORTANT: urllib3 applies connect_timeout to the socket via sock.settimeout()
# *before* sending the request body. This means connect_timeout also acts as the
# write timeout for each chunk. For large chunk uploads (e.g. 50 MB), the write
# can take significant time, so connect_timeout must be large enough to cover
# the time to send a full chunk over the network.
DEFAULT_UPLOAD_TIMEOUT = (600, 600)


@validate_call(config=VALIDATION_CONFIG)
def asset_type_path(prefix: Path | str, exec_rid: RID, asset_table: Table) -> Path:
    """Return the path to a JSON line file in which to place asset_type information.

    Args:
        prefix: Location of upload root directory
        exec_rid: Execution RID
        asset_table: Table in which to place assets.

    Returns:
        Path to the file in which to place asset_type values for the named asset.
    """
    path = execution_root(prefix, exec_rid=exec_rid) / "asset-type" / asset_table.schema.name
    path.mkdir(parents=True, exist_ok=True)
    return path / f"{asset_table.name}.jsonl"
