"""Unit tests for ``Dataset.strict_version_snapshot_catalog`` / ``strict_parents_at`` (#383 Task 7).

``_version_snapshot_catalog`` (the existing, non-strict resolver) falls back
to a **bare-catalog-id** (i.e. live) snapshot handle when a version row's
``Snapshot`` column is empty — verified fact, not a re-derivation: see
``dataset.py:_version_snapshot_catalog_id``, which returns
``self._ml_instance.catalog.catalog_id`` (no ``"@snapshot"`` suffix) on that
path, and ``_version_snapshot_catalog`` still calls ``catalog_snapshot(...)``
with that bare id rather than returning ``self._ml_instance`` directly (the
direct-return path is only for a falsy *input* version).

That live fallback is unacceptable for provenance semantics (design ruling
6: ancestry hops resolve at snapshots, never live). ``strict_version_snapshot_catalog``
is the snapshot-closed sibling that raises ``SnapshotUnavailable`` instead of
ever calling ``catalog_snapshot`` with a bare id.

``strict_parents_at`` mirrors ``list_dataset_parents``'s existing version
resolution (dataset.py:2363-2426): parents are discovered via one
``Dataset_Dataset`` fetch against the snapshot-bound catalog, then hydrated
via ``lookup_dataset`` on that same snapshot catalog. This test file adds
``parent_version_then``: the parent's own ``current_version`` (max of its
``dataset_history()``) as *observed from the child's pinned snapshot* — not
an unbounded read against the parent's live history. A parent whose
snapshot-visible version differs from its live/latest-ever version is
scripted explicitly (see ``TestStrictParentsAtVersionResolution``) to prove
the snapshot-scoped answer wins.

Offline: no live catalog. ``Dataset.__init__`` is ``@validate_call``-guarded
against the ``DerivaMLCatalog`` runtime-checkable Protocol, so plain
``MagicMock()`` catalogs (as used freely in
``tests/dataset/test_get_dataset_minid_helpers.py``, which mocks the
``Dataset`` object itself, not the catalog it wraps) fail pydantic's
``isinstance`` check. ``MagicMock(spec=DerivaMLCatalog)`` satisfies it — the
pattern used throughout this file. RIDs are generated by ``_rid()`` — never
hand-written literals.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from deriva_ml.core.exceptions import DerivaMLException, SnapshotUnavailable
from deriva_ml.dataset.aux_classes import DatasetHistory, DatasetVersion
from deriva_ml.dataset.dataset import Dataset
from deriva_ml.interfaces import DerivaMLCatalog


def _rid(n: int, prefix: str = "1") -> str:
    """Deterministic, catalog-shaped RID — never a human-written literal."""
    return f"{prefix}-{n:04X}"


def _history_row(version: str, snapshot: str | None, *, dataset_rid: str, version_rid_n: int) -> DatasetHistory:
    return DatasetHistory(
        dataset_version=DatasetVersion.parse(version),
        dataset_rid=dataset_rid,
        version_rid=_rid(version_rid_n),
        snapshot=snapshot,
    )


def _fake_catalog(catalog_id: str = "1", ml_schema: str = "deriva-ml") -> MagicMock:
    """A ``MagicMock(spec=DerivaMLCatalog)`` with a settable ``catalog.catalog_id``.

    ``spec=DerivaMLCatalog`` is what makes this pass ``Dataset.__init__``'s
    pydantic ``isinstance`` check (see module docstring) — a bare
    ``MagicMock()`` does not, because ``DerivaMLCatalog`` is a
    ``@runtime_checkable`` Protocol and pydantic's ``is_instance_of``
    validator requires every protocol attribute to actually be present.
    """
    catalog = MagicMock(spec=DerivaMLCatalog)
    catalog.ml_schema = ml_schema
    catalog.catalog = MagicMock()
    catalog.catalog.catalog_id = catalog_id
    return catalog


def _wire_dataset_dataset(catalog: MagicMock, parents_by_nested_rid: dict[str, list[str]]) -> None:
    """Wire ``catalog.pathBuilder()...Dataset_Dataset`` to return scripted parent rows.

    Mirrors the fluent chain ``list_dataset_parents``/``strict_parents_at``
    use: ``pb.schemas[ml_schema].Dataset_Dataset.filter(Nested_Dataset ==
    rid).entities().fetch()``. The ``==`` comparison on the mocked
    ``Nested_Dataset`` column returns a sentinel the mocked ``.filter()``
    uses to pick the right fetch result for the RID that was compared.
    """
    pb = MagicMock()
    dd_path = MagicMock()

    class _EqSentinel:
        def __init__(self, rid: str):
            self.rid = rid

    dd_path.Nested_Dataset.__eq__ = lambda self, rid: _EqSentinel(rid)

    def _filter(sentinel: _EqSentinel):
        parent_rids = parents_by_nested_rid.get(sentinel.rid, [])
        result = MagicMock()
        result.entities.return_value.fetch.return_value = [{"Dataset": p} for p in parent_rids]
        return result

    dd_path.filter.side_effect = _filter
    schema = MagicMock()
    schema.Dataset_Dataset = dd_path
    pb.schemas = {catalog.ml_schema: schema}
    catalog.pathBuilder.return_value = pb


def _wire_lookup_dataset(catalog: MagicMock, datasets_by_rid: dict[str, Dataset]) -> None:
    catalog.lookup_dataset.side_effect = lambda rid: datasets_by_rid[rid]


# ---------------------------------------------------------------------------
# strict_version_snapshot_catalog
# ---------------------------------------------------------------------------


class TestStrictVersionSnapshotCatalog:
    def test_falsy_snapshot_raises_snapshot_unavailable(self):
        """A version row with ``snapshot=None`` is a gap in strict mode."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot=None, dataset_rid=ds_rid, version_rid_n=10)]
        )

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("1.0.0")

    def test_falsy_snapshot_non_strict_sibling_uses_bare_id(self):
        """Companion test pinning the documented behavioral difference.

        On the SAME stub, the non-strict ``_version_snapshot_catalog``
        still calls ``catalog_snapshot`` — with the BARE catalog id (no
        ``"@snapshot"`` suffix), which is the live-fallback path. This is
        exactly the behavior ``strict_version_snapshot_catalog`` refuses.
        """
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot=None, dataset_rid=ds_rid, version_rid_n=10)]
        )
        bare_id_snapshot = _fake_catalog(catalog_id="1")
        live.catalog_snapshot.return_value = bare_id_snapshot

        result = ds._version_snapshot_catalog("1.0.0")

        live.catalog_snapshot.assert_called_once_with("1")
        assert result is bare_id_snapshot

        # And the strict sibling still refuses on the same stub.
        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("1.0.0")

    def test_falsy_snapshot_refused_even_when_ml_instance_already_snapshot_bound(self):
        """Regression pin: the discriminator must read the history row, not the id string.

        When ``self._ml_instance`` is ITSELF already a snapshot-bound
        catalog (as happens while chaining hops — e.g.
        ``strict_parents_at`` calling ``strict_version_snapshot_catalog``
        on a parent ``Dataset`` whose ``_ml_instance`` is the child's
        pinned snapshot), ``catalog.catalog_id`` is already of the form
        ``"1@SNAPA"`` — it already contains ``"@"``. A version row with a
        NULL ``Snapshot`` (the normal shape of a dev row: dev rows always
        carry ``Snapshot=NULL``, and ``current_version`` can return a dev
        label) must still be refused. A string-based ``"@" not in id``
        check would be fooled here because the BARE branch returns
        ``self._ml_instance.catalog.catalog_id`` verbatim — which already
        contains ``"@"`` — so the guard would incorrectly pass and either
        return a wrongly-scoped live catalog or a malformed
        ``"1@SNAPA@SNAPA"`` id. This test fails against that string-based
        discriminator and passes against the row-based one.
        """
        already_pinned = _fake_catalog(catalog_id="1@SNAPA")
        ds_rid = _rid(1)
        ds = Dataset(catalog=already_pinned, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("0.4.0.post1.dev3", snapshot=None, dataset_rid=ds_rid, version_rid_n=10)]
        )

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("0.4.0.post1.dev3")

        # And catalog_snapshot must never have been called with any id
        # composed from the already-"@"-bearing bare id — the whole point
        # is refusing before any id is composed at all.
        already_pinned.catalog_snapshot.assert_not_called()

    def test_catalog_snapshot_raising_is_wrapped(self):
        """An unreadable (e.g. GC'd) snapshot is wrapped as SnapshotUnavailable."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=ds_rid, version_rid_n=10)]
        )
        live.catalog_snapshot.side_effect = DerivaMLException("snapshot is unreadable")

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("1.0.0")

    def test_unknown_version_raises_snapshot_unavailable(self):
        """A version absent from history is wrapped, not the bare DerivaMLException."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("0.1.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=ds_rid, version_rid_n=10)]
        )

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("9.9.9")

    def test_happy_path_returns_snapshot_bound_instance(self):
        """A version with a real snapshot resolves via ``"<id>@<snap>"``."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=ds_rid, version_rid_n=10)]
        )
        pinned = _fake_catalog(catalog_id="1")
        live.catalog_snapshot.return_value = pinned

        result = ds.strict_version_snapshot_catalog("1.0.0")

        live.catalog_snapshot.assert_called_once_with("1@2026-01-01T00:00:00Z")
        assert result is pinned


# ---------------------------------------------------------------------------
# strict_parents_at
# ---------------------------------------------------------------------------


class TestStrictParentsAtVersionResolution:
    def test_happy_path_fk_pointer_wins_over_max_history_row(self):
        """The parent's version AT the child's snaptime wins, not its max-ever version.

        Scenario: child C is pinned at version 1.0.0, whose snapshot is
        S. Parent P's history AS VISIBLE FROM SNAPSHOT S has max version
        0.3.0. If ``strict_parents_at`` instead read the parent's LIVE
        history (a later fact, not visible from S — scripted here as
        advancing to 0.9.0 on the *live* mock, which is never consulted),
        the wrong answer would leak future state into a supposedly frozen
        closure. Only the snapshot-scoped 0.3.0 must come back.
        """
        live = _fake_catalog(catalog_id="1")
        child_rid = _rid(1)
        parent_rid = _rid(2)

        child = Dataset(catalog=live, dataset_rid=child_rid)
        child.dataset_history = MagicMock(
            return_value=[
                _history_row("1.0.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=child_rid, version_rid_n=10)
            ]
        )

        # The pinned snapshot's point of view: parent's history stops at 0.3.0.
        pinned = _fake_catalog(catalog_id="1")
        _wire_dataset_dataset(pinned, {child_rid: [parent_rid]})
        parent_at_snapshot = Dataset(catalog=pinned, dataset_rid=parent_rid)
        parent_at_snapshot.dataset_history = MagicMock(
            return_value=[
                _history_row("0.1.0", snapshot="2025-06-01T00:00:00Z", dataset_rid=parent_rid, version_rid_n=20),
                _history_row("0.3.0", snapshot="2025-12-01T00:00:00Z", dataset_rid=parent_rid, version_rid_n=21),
            ]
        )
        _wire_lookup_dataset(pinned, {parent_rid: parent_at_snapshot})
        live.catalog_snapshot.return_value = pinned

        # A LIVE-catalog Dataset for the same parent RID, wired with a
        # newer history. strict_parents_at must never touch this — if it
        # did, the assertion below would see "0.9.0" instead of "0.3.0".
        parent_live = Dataset(catalog=live, dataset_rid=parent_rid)
        parent_live.dataset_history = MagicMock(
            return_value=[
                _history_row("0.1.0", snapshot="2025-06-01T00:00:00Z", dataset_rid=parent_rid, version_rid_n=20),
                _history_row("0.3.0", snapshot="2025-12-01T00:00:00Z", dataset_rid=parent_rid, version_rid_n=21),
                _history_row("0.9.0", snapshot="2026-06-01T00:00:00Z", dataset_rid=parent_rid, version_rid_n=22),
            ]
        )
        live.lookup_dataset.side_effect = lambda rid: parent_live

        result = child.strict_parents_at("1.0.0")

        assert result == [{"parent_rid": parent_rid, "parent_version_then": "0.3.0"}]

    def test_unresolvable_parent_version_returns_none(self):
        """A parent with no version history visible at the snaptime -> None, not a raise."""
        live = _fake_catalog(catalog_id="1")
        child_rid = _rid(1)
        parent_rid = _rid(2)

        child = Dataset(catalog=live, dataset_rid=child_rid)
        child.dataset_history = MagicMock(
            return_value=[
                _history_row("1.0.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=child_rid, version_rid_n=10)
            ]
        )

        pinned = _fake_catalog(catalog_id="1")
        _wire_dataset_dataset(pinned, {child_rid: [parent_rid]})
        parent_at_snapshot = Dataset(catalog=pinned, dataset_rid=parent_rid)
        # No history visible at this snaptime -> current_version raises
        # DerivaMLException, which strict_parents_at must convert to None.
        parent_at_snapshot.dataset_history = MagicMock(return_value=[])
        _wire_lookup_dataset(pinned, {parent_rid: parent_at_snapshot})
        live.catalog_snapshot.return_value = pinned

        result = child.strict_parents_at("1.0.0")

        assert result == [{"parent_rid": parent_rid, "parent_version_then": None}]
