"""Unit tests for ``Dataset.strict_version_snapshot_catalog`` (#383 Task 7).

``_version_snapshot_catalog`` (the existing, non-strict resolver) falls back
to a **bare-catalog-id** (i.e. live) snapshot handle when a version row's
``Snapshot`` column is empty — verified fact, not a re-derivation: see
``dataset.py:_version_snapshot_catalog_id``, which returns
``self._ml_instance.catalog.catalog_id`` (no ``"@snapshot"`` suffix) on that
path, and ``_version_snapshot_catalog`` still calls ``catalog_snapshot(...)``
with that bare id rather than returning ``self._ml_instance`` directly (the
direct-return path is only for a falsy *input* version).

That live fallback is unacceptable for provenance semantics: a pinned
closure must never let post-snaptime state leak in through a silent live
read. ``strict_version_snapshot_catalog`` is the snapshot-closed sibling
that raises ``SnapshotUnavailable`` instead of ever calling
``catalog_snapshot`` with a bare id. It gates the closure's
version-authorship and member-binding legs.

(The ``strict_parents_at`` sibling this file used to cover was removed with
the ancestry leg — ruling 8, #389: containment is structure, not
provenance.)

Offline: no live catalog. ``Dataset.__init__`` is ``@validate_call``-guarded
against the ``DerivaMLCatalog`` runtime-checkable Protocol, so plain
``MagicMock()`` catalogs (as used freely in
``tests/dataset/test_get_dataset_minid_helpers.py``, which mocks the
``Dataset`` object itself, not the catalog it wraps) fail pydantic's
``isinstance`` check. ``MagicMock(spec=DerivaMLCatalog)`` satisfies it — the
pattern used throughout this file. RIDs are generated by ``_rid()`` — never
hand-written literals.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from deriva_ml.core.exceptions import DerivaMLException, SnapshotUnavailable
from deriva_ml.dataset.aux_classes import DatasetHistory, DatasetVersion
from deriva_ml.dataset.dataset import Dataset
from deriva_ml.interfaces import DerivaMLCatalog


def _rid(n: int, prefix: str = "1") -> str:
    """Deterministic, catalog-shaped RID — never a human-written literal."""
    return f"{prefix}-{n:04X}"


def _history_row(version: str, snapshot: str | None, *, dataset_rid: str, version_rid_n: int) -> DatasetHistory:
    return DatasetHistory(
        dataset_version=DatasetVersion.parse(version),
        dataset_rid=dataset_rid,
        version_rid=_rid(version_rid_n),
        snapshot=snapshot,
    )


def _fake_catalog(catalog_id: str = "1", ml_schema: str = "deriva-ml") -> MagicMock:
    """A ``MagicMock(spec=DerivaMLCatalog)`` with a settable ``catalog.catalog_id``.

    ``spec=DerivaMLCatalog`` is what makes this pass ``Dataset.__init__``'s
    pydantic ``isinstance`` check (see module docstring) — a bare
    ``MagicMock()`` does not, because ``DerivaMLCatalog`` is a
    ``@runtime_checkable`` Protocol and pydantic's ``is_instance_of``
    validator requires every protocol attribute to actually be present.
    """
    catalog = MagicMock(spec=DerivaMLCatalog)
    catalog.ml_schema = ml_schema
    catalog.catalog = MagicMock()
    catalog.catalog.catalog_id = catalog_id
    return catalog


# ---------------------------------------------------------------------------
# strict_version_snapshot_catalog
# ---------------------------------------------------------------------------


class TestStrictVersionSnapshotCatalog:
    def test_falsy_snapshot_raises_snapshot_unavailable(self):
        """A version row with ``snapshot=None`` is a gap in strict mode."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot=None, dataset_rid=ds_rid, version_rid_n=10)]
        )

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("1.0.0")

    def test_falsy_snapshot_non_strict_sibling_uses_bare_id(self):
        """Companion test pinning the documented behavioral difference.

        On the SAME stub, the non-strict ``_version_snapshot_catalog``
        still calls ``catalog_snapshot`` — with the BARE catalog id (no
        ``"@snapshot"`` suffix), which is the live-fallback path. This is
        exactly the behavior ``strict_version_snapshot_catalog`` refuses.
        """
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot=None, dataset_rid=ds_rid, version_rid_n=10)]
        )
        bare_id_snapshot = _fake_catalog(catalog_id="1")
        live.catalog_snapshot.return_value = bare_id_snapshot

        result = ds._version_snapshot_catalog("1.0.0")

        live.catalog_snapshot.assert_called_once_with("1")
        assert result is bare_id_snapshot

        # And the strict sibling still refuses on the same stub.
        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("1.0.0")

    def test_falsy_snapshot_refused_even_when_ml_instance_already_snapshot_bound(self):
        """Regression pin: the discriminator must read the history row, not the id string.

        When ``self._ml_instance`` is ITSELF already a snapshot-bound
        catalog (as happens whenever a ``Dataset`` handle is obtained from
        an already-pinned catalog and then asked to resolve one of its own
        versions), ``catalog.catalog_id`` is already of the form
        ``"1@SNAPA"`` — it already contains ``"@"``. A version row with a
        NULL ``Snapshot`` (the normal shape of a dev row: dev rows always
        carry ``Snapshot=NULL``, and ``current_version`` can return a dev
        label) must still be refused. A string-based ``"@" not in id``
        check would be fooled here because the BARE branch returns
        ``self._ml_instance.catalog.catalog_id`` verbatim — which already
        contains ``"@"`` — so the guard would incorrectly pass and either
        return a wrongly-scoped live catalog or a malformed
        ``"1@SNAPA@SNAPA"`` id. This test fails against that string-based
        discriminator and passes against the row-based one.
        """
        already_pinned = _fake_catalog(catalog_id="1@SNAPA")
        ds_rid = _rid(1)
        ds = Dataset(catalog=already_pinned, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("0.4.0.post1.dev3", snapshot=None, dataset_rid=ds_rid, version_rid_n=10)]
        )

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("0.4.0.post1.dev3")

        # And catalog_snapshot must never have been called with any id
        # composed from the already-"@"-bearing bare id — the whole point
        # is refusing before any id is composed at all.
        already_pinned.catalog_snapshot.assert_not_called()

    def test_catalog_snapshot_raising_is_wrapped(self):
        """An unreadable (e.g. GC'd) snapshot is wrapped as SnapshotUnavailable."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=ds_rid, version_rid_n=10)]
        )
        live.catalog_snapshot.side_effect = DerivaMLException("snapshot is unreadable")

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("1.0.0")

    def test_unknown_version_raises_snapshot_unavailable(self):
        """A version absent from history is wrapped, not the bare DerivaMLException."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("0.1.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=ds_rid, version_rid_n=10)]
        )

        with pytest.raises(SnapshotUnavailable):
            ds.strict_version_snapshot_catalog("9.9.9")

    def test_happy_path_returns_snapshot_bound_instance(self):
        """A version with a real snapshot resolves via ``"<id>@<snap>"``."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        ds.dataset_history = MagicMock(
            return_value=[_history_row("1.0.0", snapshot="2026-01-01T00:00:00Z", dataset_rid=ds_rid, version_rid_n=10)]
        )
        pinned = _fake_catalog(catalog_id="1")
        live.catalog_snapshot.return_value = pinned

        result = ds.strict_version_snapshot_catalog("1.0.0")

        live.catalog_snapshot.assert_called_once_with("1@2026-01-01T00:00:00Z")
        assert result is pinned


class TestSnapshotSchemaEvolutionDegradesToGap:
    """A snapshot-bound read sees the schema as it stood at that snaptime.

    A column added later is simply absent there, which deriva-py surfaces
    as ``AttributeError`` (datapath attribute access) or ``KeyError`` (row
    indexing) — neither a ``DerivaMLException``. Before the fix these
    escaped ``lookup_provenance`` as hard crashes; the strict layer now
    converts them to ``SnapshotUnavailable`` so the engine can degrade
    them to a ``snapshot_chain_break`` gap.

    Observed live on eye-ai: ``Dataset_Version.Snapshot`` absent at
    v1.0.0-4.1.0 snaptimes (KeyError, via ``dataset_history``).
    """

    def test_key_error_reading_version_history_becomes_snapshot_unavailable(self):
        """Missing history column at the snaptime (KeyError) -> SnapshotUnavailable."""
        live = _fake_catalog(catalog_id="1")
        ds_rid = _rid(1)
        ds = Dataset(catalog=live, dataset_rid=ds_rid)
        # dataset_history indexes v["Snapshot"], absent in the old
        # Dataset_Version schema this dataset's snapshot exposes.
        ds.dataset_history = MagicMock(side_effect=KeyError("Snapshot"))

        with pytest.raises(SnapshotUnavailable) as excinfo:
            ds.strict_version_snapshot_catalog("1.0.0")

        assert "Snapshot" in str(excinfo.value)
