"""Unit tests for ``DerivaML.lookup_provenance`` (Task 10 — consumption closure).

These reuse the ``_FakeML`` harness from ``test_lookup_lineage_unit`` (its
Task 8 closure seams: snapshot availability, parents-at, binding scans, and
``ml.calls`` recording) so the closure walk is exercised entirely offline.

Scope pinned here is Task 10's slice of the design
(``docs/superpowers/specs/2026-08-31-lookup-provenance-design.md``):

- root typology + root-version resolution rule (§3),
- ``ArcKind.root`` at depth 0 and ``ArcKind.consumption`` arcs carrying
  concrete inputs (§6.1),
- the assets map with ALL producers and its two gap kinds (§6.2),
- ``no_workflow`` / ``unresolved_rid`` / ``sentinel_origin`` gaps,
- the unpinned-input quarantine (gap + ``not_walked`` facts + provably zero
  snapshot-dependent seam calls),
- arc-identity dedup with minimum depth, and the strict execution budget.

The dataset-side arcs (version authorship, member bindings, ancestry) land
in Tasks 11-13 and are deliberately NOT asserted here.

Every RID is generated by ``_rid`` — never a hand-written literal (the
repo-wide RID discipline).
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from deriva_ml.core.exceptions import DerivaMLValidationError
from deriva_ml.execution.provenance import (
    AncestryState,
    ArcInputType,
    ArcKind,
    GapKind,
    ProvenanceClosure,
)
from tests.execution.test_lookup_lineage_unit import (
    _FakeML,
    _StubAsset,
    _StubDataset,
    _StubWorkflow,
)

# ---------------------------------------------------------------------------
# Helpers.
# ---------------------------------------------------------------------------


def _rid(n: int, prefix: str = "1") -> str:
    """Generate a deterministic, catalog-shaped RID.

    Never a human-written literal — every RID in this module comes from
    here, matching the codebase-wide RID discipline.
    """
    return f"{prefix}-{n:04X}"


def _ds(n: int) -> str:
    return _rid(n, prefix="1")


def _ex(n: int) -> str:
    return _rid(n, prefix="2")


def _wf(n: int) -> str:
    return _rid(n, prefix="3")


def _as(n: int) -> str:
    return _rid(n, prefix="4")


def _fv(n: int) -> str:
    return _rid(n, prefix="5")


def _arcs_of(closure: ProvenanceClosure, rid: str):
    return closure.executions[rid].arcs


def _gaps_for(closure: ProvenanceClosure, kind: GapKind, subject: str | None = None):
    return [g for g in closure.gaps if g.kind == kind and (subject is None or g.subject_rid == subject)]


# ---------------------------------------------------------------------------
# Consumption closure — reach and concrete inputs.
# ---------------------------------------------------------------------------


def test_dataset_root_two_level_closure_reaches_all_executions():
    """DS2 <- EXB <- DS1 <- EXA <- DS0: both executions enter the closure,
    each with a consumption arc naming the concrete input rid + version."""
    ml = _FakeML()
    ds0, ds1, ds2 = _ds(1), _ds(2), _ds(3)
    exa, exb = _ex(1), _ex(2)

    ml.add_dataset(ds0, description="raw", producer=None)
    ml.add_dataset(ds1, description="curated", producer=exa)
    ml.add_dataset(ds2, description="trained", producer=exb)
    ml.add_execution(
        exa,
        description="curate",
        workflow=_StubWorkflow(workflow_rid=_wf(1), name="curator"),
        input_datasets=[_StubDataset(ds0, "raw", "0.1.0", consumed_version="0.1.0")],
    )
    ml.add_execution(
        exb,
        description="train",
        workflow=_StubWorkflow(workflow_rid=_wf(2), name="trainer"),
        input_datasets=[_StubDataset(ds1, "curated", "1.0.0", consumed_version="1.0.0")],
    )
    ml.set_versioned_producer(ds1, "1.0.0", exa)

    closure = ml.lookup_provenance(ds2)

    assert isinstance(closure, ProvenanceClosure)
    assert set(closure.executions) == {exa, exb}
    assert closure.executions_visited == 2
    assert closure.traversal_complete is True
    assert closure.cap_hit is False

    # EXB is the root artifact's producer; EXA is in the closure because it
    # produced DS1@1.0.0, which EXB consumed — so the consumption arc lands
    # on EXA (the producer) naming the concrete input and its pinned version.
    assert [a.kind for a in _arcs_of(closure, exb)] == [ArcKind.root]

    exa_consumption = [a for a in _arcs_of(closure, exa) if a.kind == ArcKind.consumption]
    assert len(exa_consumption) == 1
    assert exa_consumption[0].input_rid == ds1
    assert exa_consumption[0].input_version == "1.0.0"
    assert exa_consumption[0].input_type == ArcInputType.dataset
    assert exa_consumption[0].consumed_by == exb
    assert exa_consumption[0].depth == 1

    # DS0 has no producer, so nothing enters the closure through it — but
    # both consumption edges were still observed as dataset facts.
    assert {ds0, ds1} <= set(closure.datasets)


def test_root_arc_on_execution_root():
    ml = _FakeML()
    exa = _ex(1)
    ml.add_execution(exa, description="solo", workflow=_StubWorkflow(workflow_rid=_wf(1), name="w"))

    closure = ml.lookup_provenance(exa)

    assert closure.root.type == "Execution"
    root_arcs = [a for a in _arcs_of(closure, exa) if a.kind == ArcKind.root]
    assert len(root_arcs) == 1
    assert root_arcs[0].depth == 0


def test_root_arc_on_dataset_root_producer():
    ml = _FakeML()
    ds1, exa = _ds(1), _ex(1)
    ml.add_execution(exa, description="make", workflow=_StubWorkflow(workflow_rid=_wf(1), name="w"))
    ml.add_dataset(ds1, description="made", producer=exa)

    closure = ml.lookup_provenance(ds1)

    root_arcs = [a for a in _arcs_of(closure, exa) if a.kind == ArcKind.root]
    assert len(root_arcs) == 1
    assert root_arcs[0].depth == 0


# ---------------------------------------------------------------------------
# Feature-value roots (spec §3, v1).
# ---------------------------------------------------------------------------


def test_feature_value_root_closure():
    """A feature value's closure is its binding execution + that execution's
    own ancestry."""
    ml = _FakeML()
    fv, binder, upstream = _fv(1), _ex(1), _ex(2)
    ds0 = _ds(1)

    ml.add_dataset(ds0, description="raw", producer=upstream)
    ml.add_execution(upstream, description="ingest", workflow=_StubWorkflow(workflow_rid=_wf(2), name="ingest"))
    ml.add_execution(
        binder,
        description="annotate",
        workflow=_StubWorkflow(workflow_rid=_wf(1), name="annotator"),
        input_datasets=[_StubDataset(ds0, "raw", "0.1.0", consumed_version="0.1.0")],
    )
    ml.add_feature_value(fv, producer_execution=binder)
    ml.set_versioned_producer(ds0, "0.1.0", upstream)

    closure = ml.lookup_provenance(fv)

    assert closure.root.type == "Feature"
    assert set(closure.executions) == {binder, upstream}
    assert any(a.kind == ArcKind.root and a.depth == 0 for a in _arcs_of(closure, binder))


def test_feature_value_root_null_execution_gap():
    ml = _FakeML()
    fv = _fv(1)
    ml.add_feature_value(fv, producer_execution=None)

    closure = ml.lookup_provenance(fv)

    assert closure.executions == {}
    gaps = _gaps_for(closure, GapKind.null_binding_execution, fv)
    assert len(gaps) == 1


def test_feature_value_root_sentinel_gap():
    ml = _FakeML()
    fv, sentinel = _fv(1), _ex(66)
    ml.add_execution(sentinel, description="unknown provenance")
    ml.add_feature_value(fv, producer_execution=sentinel)
    ml._sentinel_execution_rid_or_none = lambda: sentinel  # type: ignore[method-assign]

    closure = ml.lookup_provenance(fv)

    assert sentinel not in closure.executions
    assert _gaps_for(closure, GapKind.sentinel_origin, sentinel)


def test_feature_value_root_unresolvable_binding_gap():
    """A binding execution RID that does not resolve is an ``unresolved_rid``
    gap, not a crash."""
    ml = _FakeML()
    fv, ghost = _fv(1), _ex(99)
    ml.add_feature_value(fv, producer_execution=ghost)

    closure = ml.lookup_provenance(fv)

    assert closure.executions == {}
    assert _gaps_for(closure, GapKind.unresolved_rid, ghost)


# ---------------------------------------------------------------------------
# Root version resolution (spec §3).
# ---------------------------------------------------------------------------


def test_root_version_explicit_historical():
    ml = _FakeML()
    ds1, exa, exb = _ds(1), _ex(1), _ex(2)
    ml.add_dataset(ds1, description="versioned")
    ml.add_version_row(ds1, "0.1.0", exa, rct="2025-01-01T00:00:00Z")
    ml.add_version_row(ds1, "0.2.0", exb, rct="2026-01-01T00:00:00Z")
    ml.add_execution(exa, description="origin")
    ml.add_execution(exb, description="later")

    closure = ml.lookup_provenance(ds1, version="0.1.0")

    assert closure.root.version == "0.1.0"


def test_root_version_omitted_resolves_latest():
    """Latest by ``_version_row_sort_key`` (RCT-primary), NOT by list order or
    RID order — the rows are scripted out of chronological order on purpose."""
    ml = _FakeML()
    ds1, exa, exb = _ds(1), _ex(1), _ex(2)
    ml.add_dataset(ds1, description="versioned")
    # Appended newest-first: only an RCT-aware max picks 4.13.0.
    ml.add_version_row(ds1, "4.13.0", exb, rct="2026-01-01T00:00:00Z")
    ml.add_version_row(ds1, "0.1.0", exa, rct="2025-01-01T00:00:00Z")
    ml.add_execution(exa, description="origin")
    ml.add_execution(exb, description="later")

    closure = ml.lookup_provenance(ds1)

    assert closure.root.version == "4.13.0"


def test_root_version_unknown_raises_validation_error():
    ml = _FakeML()
    ds1, exa = _ds(1), _ex(1)
    ml.add_dataset(ds1, description="versioned")
    ml.add_version_row(ds1, "0.1.0", exa)
    ml.add_execution(exa)

    with pytest.raises(DerivaMLValidationError, match="9.9.9"):
        ml.lookup_provenance(ds1, version="9.9.9")


def test_dataset_with_no_version_rows_gap_and_degraded_walk():
    """No version rows at all: ``version_unresolvable`` gap, ``root.version``
    stays None, and the walk still runs on non-snapshot arcs."""
    ml = _FakeML()
    ds1, exa = _ds(1), _ex(1)
    ml._rids[ds1] = ("Dataset", set(), {"Description": "no versions"})
    ml.set_member_producers(ds1, {exa})
    ml.add_execution(exa, description="member producer")

    closure = ml.lookup_provenance(ds1)

    assert closure.root.version is None
    assert _gaps_for(closure, GapKind.version_unresolvable, ds1)
    # Degraded but not empty: the member producer still enters the closure.
    assert exa in closure.executions


def test_version_kwarg_on_execution_root_raises():
    ml = _FakeML()
    exa = _ex(1)
    ml.add_execution(exa)

    with pytest.raises(DerivaMLValidationError, match="Dataset"):
        ml.lookup_provenance(exa, version="0.1.0")


# ---------------------------------------------------------------------------
# Budget validation.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("bad", [0, -1, True, "2", 2.5])
def test_max_executions_strict_boundary(bad):
    """Strict int ge=1: zero, negative, bool, str, and float all rejected at
    the call boundary (the repo's VALIDATION_CONFIG is non-strict, so
    ``Field(strict=True)`` is what makes ``True`` and ``"2"`` fail)."""
    ml = _FakeML()
    exa = _ex(1)
    ml.add_execution(exa)

    with pytest.raises(ValidationError):
        ml.lookup_provenance(exa, max_executions=bad)


def test_cap_sets_traversal_complete_false():
    ml = _FakeML()
    ds0, ds1, ds2 = _ds(1), _ds(2), _ds(3)
    exa, exb = _ex(1), _ex(2)
    ml.add_dataset(ds0, producer=None)
    ml.add_dataset(ds1, producer=exa)
    ml.add_dataset(ds2, producer=exb)
    ml.add_execution(exa, input_datasets=[_StubDataset(ds0, consumed_version="0.1.0")])
    ml.add_execution(exb, input_datasets=[_StubDataset(ds1, consumed_version="1.0.0")])
    ml.set_versioned_producer(ds1, "1.0.0", exa)

    closure = ml.lookup_provenance(ds2, max_executions=1)

    assert closure.traversal_complete is False
    assert closure.cap_hit is True
    assert closure.executions_visited == 1


# ---------------------------------------------------------------------------
# Arc identity: distinct inputs vs rediscovery.
# ---------------------------------------------------------------------------


def test_diamond_two_distinct_consumption_arcs():
    """One shared producer reached through two DIFFERENT inputs yields TWO
    consumption arcs (different input_rid ⇒ different identity)."""
    ml = _FakeML()
    ds_left, ds_right, ds_root = _ds(1), _ds(2), _ds(3)
    shared, consumer = _ex(1), _ex(2)

    ml.add_dataset(ds_left, description="left", producer=shared)
    ml.add_dataset(ds_right, description="right", producer=shared)
    ml.add_dataset(ds_root, description="root", producer=consumer)
    ml.add_execution(shared, description="fan-out producer")
    ml.add_execution(
        consumer,
        description="joins both",
        input_datasets=[
            _StubDataset(ds_left, "left", "1.0.0", consumed_version="1.0.0"),
            _StubDataset(ds_right, "right", "1.0.0", consumed_version="1.0.0"),
        ],
    )
    ml.set_versioned_producer(ds_left, "1.0.0", shared)
    ml.set_versioned_producer(ds_right, "1.0.0", shared)

    closure = ml.lookup_provenance(ds_root)

    consumption = [a for a in _arcs_of(closure, shared) if a.kind == ArcKind.consumption]
    assert len(consumption) == 2
    assert {a.input_rid for a in consumption} == {ds_left, ds_right}


def test_same_identity_rediscovery_dedups_min_depth():
    """The same (kind, consumer, input, version) fact discovered at two
    depths collapses to ONE arc carrying the minimum depth."""
    ml = _FakeML()
    ds_shared, ds_mid, ds_root = _ds(1), _ds(2), _ds(3)
    producer, mid, top = _ex(1), _ex(2), _ex(3)

    ml.add_dataset(ds_shared, description="shared", producer=producer)
    ml.add_dataset(ds_mid, description="mid", producer=mid)
    ml.add_dataset(ds_root, description="root", producer=top)
    ml.add_execution(producer, description="produces shared")
    # `mid` consumes the shared dataset...
    ml.add_execution(mid, description="mid", input_datasets=[_StubDataset(ds_shared, consumed_version="1.0.0")])
    # ...and so does `top`, at a shallower depth, plus it consumes mid's output.
    ml.add_execution(
        top,
        description="top",
        input_datasets=[
            _StubDataset(ds_mid, consumed_version="1.0.0"),
            _StubDataset(ds_shared, consumed_version="1.0.0"),
        ],
    )
    ml.set_versioned_producer(ds_shared, "1.0.0", producer)
    ml.set_versioned_producer(ds_mid, "1.0.0", mid)

    closure = ml.lookup_provenance(ds_root)

    # `producer` was reached from `top` (depth 1) and from `mid` (depth 2),
    # but only the top arc identity repeats per consumer, so assert on the
    # per-consumer arc: exactly one arc per (consumer, input) pair.
    identities = [a.identity() for a in _arcs_of(closure, producer)]
    assert len(identities) == len(set(identities))

    # The shared dataset is consumed by BOTH top and mid — two distinct
    # identities (different consumed_by), each recorded once.
    shared_arcs = [a for a in _arcs_of(closure, producer) if a.input_rid == ds_shared]
    assert {a.consumed_by for a in shared_arcs} == {top, mid}
    # Arc depth is the PRODUCER's hop count from the root: reached from
    # `top` (root, depth 0) the producer sits at depth 1; reached from `mid`
    # (depth 1) it sits at depth 2.
    by_consumer = {a.consumed_by: a for a in shared_arcs}
    assert by_consumer[top].depth == 1
    assert by_consumer[mid].depth == 2


def test_rediscovery_at_shallower_depth_lowers_recorded_depth():
    """A literal re-emission of the SAME arc identity at a shallower depth
    lowers the recorded depth rather than appending a second arc."""
    from deriva_ml.core.mixins._provenance_engine import ClosureBuilder

    builder = ClosureBuilder()
    consumer, producer, ds = _ex(1), _ex(2), _ds(1)
    builder.record_arc(
        producer,
        kind=ArcKind.consumption,
        depth=3,
        consumed_by=consumer,
        input_rid=ds,
        input_type=ArcInputType.dataset,
        input_version="1.0.0",
    )
    builder.record_arc(
        producer,
        kind=ArcKind.consumption,
        depth=1,
        consumed_by=consumer,
        input_rid=ds,
        input_type=ArcInputType.dataset,
        input_version="1.0.0",
    )

    arcs = builder.arcs_for(producer)
    assert len(arcs) == 1
    assert arcs[0].depth == 1


# ---------------------------------------------------------------------------
# Engine bookkeeping (carried Task 9 review findings).
# ---------------------------------------------------------------------------


def test_unpinned_edge_does_not_consume_dataset_budget():
    """Carried finding (a): an unpinned edge is a quarantine, not an
    expansion — it must not count toward ``datasets_visited`` or eat the
    dataset budget, because nothing was walked."""
    from deriva_ml.core.mixins._provenance_engine import ClosureBuilder, WalkEngine

    builder = ClosureBuilder()
    engine = WalkEngine(None, builder, max_executions=10, dataset_budget=1, closure_mode=True)

    engine.expand_dataset(_ds(1), None, depth=0)
    assert engine.datasets_visited == 0
    assert engine.cap_hit is False

    # A single pinned expansion still fits the budget of 1 — it would not
    # have, had the unpinned edge consumed a slot.
    engine.expand_dataset(_ds(2), "1.0.0", depth=0)
    assert engine.datasets_visited == 1
    assert engine.cap_hit is False


def test_drain_stops_at_cap_and_marks_it():
    """A queue that outlives the execution budget stops the drain and
    reports the traversal as incomplete rather than silently truncating."""
    from deriva_ml.core.mixins._provenance_engine import ClosureBuilder, WalkEngine

    ml = _FakeML()
    exa, exb = _ex(1), _ex(2)
    ml.add_execution(exa, description="a")
    ml.add_execution(exb, description="b")

    builder = ClosureBuilder()
    engine = WalkEngine(ml, builder, max_executions=1, closure_mode=True)
    engine.enqueue_execution(exa, depth=1)
    engine.enqueue_execution(exb, depth=1)
    engine.drain(depth_remaining=None)

    assert engine.executions_visited == 1
    assert engine.cap_hit is True
    assert engine.flags["walked_complete"] is False


def test_arc_target_that_never_became_a_member_is_not_in_executions():
    """``build_executions`` keys off resolved summaries, so an arc recorded
    against a RID that never expanded yields no half-empty member — the
    RID's absence is what the closure's gaps then have to explain."""
    from deriva_ml.core.mixins._provenance_engine import ClosureBuilder

    builder = ClosureBuilder()
    ghost, consumer = _ex(99), _ex(1)
    builder.record_arc(ghost, kind=ArcKind.consumption, depth=1, consumed_by=consumer)

    assert builder.arcs_for(ghost)  # the arc was recorded...
    assert builder.build_executions() == {}  # ...but no member was fabricated


# ---------------------------------------------------------------------------
# Assets (§6.2).
# ---------------------------------------------------------------------------


def test_asset_two_producers_all_reported_plus_gap():
    ml = _FakeML()
    asset, prod_a, prod_b, consumer, ds_root = _as(1), _ex(1), _ex(2), _ex(3), _ds(1)
    ml.add_asset(asset, "Execution_Asset", filename="w.pt", producers=[prod_b, prod_a])
    ml.add_execution(prod_a, description="a")
    ml.add_execution(prod_b, description="b")
    ml.add_execution(
        consumer,
        description="consumer",
        input_assets=[_StubAsset(asset_rid=asset, filename="w.pt", asset_table="Execution_Asset")],
    )
    ml.add_dataset(ds_root, producer=consumer)

    closure = ml.lookup_provenance(ds_root)

    assert asset in closure.assets
    # Fetched order preserved verbatim (prod_b first, as scripted).
    assert closure.assets[asset].producers == [prod_b, prod_a]
    assert closure.assets[asset].consumed_by == [consumer]
    assert _gaps_for(closure, GapKind.multiple_asset_producers, asset)
    # Both producers enter the closure with consumption arcs.
    assert {prod_a, prod_b} <= set(closure.executions)


def test_asset_zero_producers_gap():
    ml = _FakeML()
    asset, consumer, ds_root = _as(1), _ex(1), _ds(1)
    ml.add_asset(asset, "Execution_Asset", filename="in.csv", producers=[])
    ml.add_execution(
        consumer,
        description="consumer",
        input_assets=[_StubAsset(asset_rid=asset, filename="in.csv", asset_table="Execution_Asset")],
    )
    ml.add_dataset(ds_root, producer=consumer)

    closure = ml.lookup_provenance(ds_root)

    assert closure.assets[asset].producers == []
    assert _gaps_for(closure, GapKind.no_asset_producer, asset)


# ---------------------------------------------------------------------------
# Execution-level gaps.
# ---------------------------------------------------------------------------


def test_execution_without_workflow_gap():
    ml = _FakeML()
    exa, ds_root = _ex(1), _ds(1)
    ml.add_execution(exa, description="no workflow", workflow=None)
    ml.add_dataset(ds_root, producer=exa)

    closure = ml.lookup_provenance(ds_root)

    assert _gaps_for(closure, GapKind.no_workflow, exa)


def test_unresolved_rid_gap_mid_walk():
    """A parent execution RID that does not resolve mid-walk becomes an
    ``unresolved_rid`` gap; the rest of the walk continues."""
    ml = _FakeML()
    ds_root, ds_in, good, ghost = _ds(1), _ds(2), _ex(1), _ex(99)
    ml.add_dataset(ds_in, description="input", producer=ghost)
    ml.set_versioned_producer(ds_in, "1.0.0", ghost)
    ml.add_execution(good, description="good", input_datasets=[_StubDataset(ds_in, consumed_version="1.0.0")])
    ml.add_dataset(ds_root, producer=good)

    closure = ml.lookup_provenance(ds_root)

    assert good in closure.executions
    assert ghost not in closure.executions
    assert _gaps_for(closure, GapKind.unresolved_rid, ghost)


def test_sentinel_never_expanded_gap_emitted():
    """The unknown-provenance sentinel never becomes a closure member, even
    when it is a recorded producer of a consumed input."""
    ml = _FakeML()
    ds_root, ds_in, consumer, sentinel = _ds(1), _ds(2), _ex(1), _ex(66)
    ml.add_execution(sentinel, description="unknown provenance")
    ml.add_dataset(ds_in, description="input", producer=sentinel)
    ml.set_versioned_producer(ds_in, "1.0.0", sentinel)
    ml.add_execution(consumer, description="consumer", input_datasets=[_StubDataset(ds_in, consumed_version="1.0.0")])
    ml.add_dataset(ds_root, producer=consumer)
    ml._sentinel_execution_rid_or_none = lambda: sentinel  # type: ignore[method-assign]

    closure = ml.lookup_provenance(ds_root)

    assert sentinel not in closure.executions
    assert _gaps_for(closure, GapKind.sentinel_origin, sentinel)
    assert consumer in closure.executions
    # The sentinel resolves fine — it is excluded by design, so calling it
    # "unresolved" would be a dishonest gap on top of the honest one.
    assert not _gaps_for(closure, GapKind.unresolved_rid, sentinel)


# ---------------------------------------------------------------------------
# Unpinned-input quarantine (§6.1).
# ---------------------------------------------------------------------------


def test_unpinned_input_quarantined_no_snapshot_calls():
    """An unpinned dataset input yields an ``unpinned_input`` gap and
    ``not_walked`` facts, and provably makes ZERO snapshot-dependent seam
    calls for that dataset."""
    ml = _FakeML()
    ds_root, ds_unpinned, consumer = _ds(1), _ds(2), _ex(1)
    ml.add_dataset(ds_unpinned, description="unpinned input", producer=None)
    ml.add_execution(
        consumer,
        description="consumer",
        input_datasets=[_StubDataset(ds_unpinned, "unpinned input", "1.0.0", consumed_version=None)],
    )
    ml.add_dataset(ds_root, producer=consumer)
    ml.calls.clear()

    closure = ml.lookup_provenance(ds_root)

    assert _gaps_for(closure, GapKind.unpinned_input, ds_unpinned)
    facts = closure.datasets[ds_unpinned].versions
    assert len(facts) == 1
    only = next(iter(facts.values()))
    assert only.ancestry_state == AncestryState.not_walked
    assert only.is_source is None

    snapshot_dependent = {
        "Dataset.strict_version_snapshot_catalog",
        "Dataset.strict_parents_at",
        "_find_feature_producers_impl",
        "lookup_dataset",
    }
    offending = [c for c in ml.calls if c[0] in snapshot_dependent and ds_unpinned in c[1]]
    assert offending == [], f"snapshot-dependent calls leaked for the unpinned dataset: {offending}"
    # The version-history read is also snapshot-flavored authorship work and
    # must not fire for a quarantined dataset.
    assert not [c for c in ml.calls if c[0] == "_dataset_version_rows" and c[1] == (ds_unpinned,)]


# ---------------------------------------------------------------------------
# Serialization.
# ---------------------------------------------------------------------------


def test_closure_round_trips_through_model_dump():
    import json

    ml = _FakeML()
    ds_root, exa = _ds(1), _ex(1)
    ml.add_execution(exa, description="make", workflow=_StubWorkflow(workflow_rid=_wf(1), name="w"))
    ml.add_dataset(ds_root, producer=exa)

    closure = ml.lookup_provenance(ds_root)
    dumped = closure.model_dump(mode="json")

    assert isinstance(json.dumps(dumped), str)
    assert ProvenanceClosure.model_validate(dumped) == closure
