name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    outputs:
      artifact-name: dist
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: supplypike/setup-bin@v4
        with:
          name: uv
          version: latest
          uri: https://astral.sh/uv/install.sh

      - name: Prepend ~/.local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build package
        run: uv build --verbose

      - name: Upload built dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Draft GitHub Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build, create-release]
    environment: publish  # Optional GitHub environment to protect this step
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: supplypike/setup-bin@v4
        with:
          name: uv
          version: latest
          uri: https://astral.sh/uv/install.sh

      - name: Prepend ~/.local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Download built dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Debug artifact contents
        run: ls -l dist/

      - name: Publish to PyPI
        run: uv publish --verbose
 
