name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.2.3

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: supplypike/setup-bin@v3
        with:
          toolName: uv
          version: latest
          uri: https://astral.sh/uv/install.sh

      - name: Build the package
        run: uv build

      - name: Publish to PyPI
        run: uv publish

  create-release:
    name: Create GitHub Release with notes
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate GitHub Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true  # 👈 This tells it to publish, not draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}